#!/usr/bin/env node

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

try {
    // Get git commit hash (short form)
    const gitHash = execSync('git rev-parse --short HEAD', { encoding: 'utf-8' }).trim();

    // Get current timestamp
    const buildTime = new Date().toISOString();

    // Create version object
    const versionInfo = {
        hash: gitHash,
        buildTime: buildTime,
        version: `v${gitHash}`
    };

    // Generate TypeScript file
    const content = `// This file is auto-generated by generate-version.js
// Do not edit manually

export const VERSION_INFO = ${JSON.stringify(versionInfo, null, 2)};
`;

    // Write to src/version.ts
    const outputPath = path.join(__dirname, 'src', 'version.ts');
    fs.writeFileSync(outputPath, content, 'utf-8');

    console.log(`✅ Version file generated: ${versionInfo.version}`);
    console.log(`   Git Hash: ${gitHash}`);
    console.log(`   Build Time: ${buildTime}`);
} catch (error) {
    console.error('❌ Error generating version file:', error.message);

    // Fallback version if git is not available
    const fallbackVersion = {
        hash: 'dev',
        buildTime: new Date().toISOString(),
        version: 'v-dev'
    };

    const content = `// This file is auto-generated by generate-version.js
// Do not edit manually

export const VERSION_INFO = ${JSON.stringify(fallbackVersion, null, 2)};
`;

    const outputPath = path.join(__dirname, 'src', 'version.ts');
    fs.writeFileSync(outputPath, content, 'utf-8');

    console.log('⚠️  Using fallback version (git not available)');
}
