#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

try {
    // Read version from package.json
    const packageJsonPath = path.join(__dirname, 'package.json');
    const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));
    const version = packageJson.version;

    // Get current timestamp
    const buildTime = new Date().toISOString();

    // Create version object
    const versionInfo = {
        version: `v${version}`,
        buildTime: buildTime
    };

    // Generate TypeScript file
    const content = `// This file is auto-generated by generate-version.js
// Do not edit manually

export const VERSION_INFO = ${JSON.stringify(versionInfo, null, 2)};
`;

    // Write to src/version.ts
    const outputPath = path.join(__dirname, 'src', 'version.ts');
    fs.writeFileSync(outputPath, content, 'utf-8');

    console.log(`✅ Version file generated: ${versionInfo.version}`);
    console.log(`   Build Time: ${buildTime}`);
} catch (error) {
    console.error('❌ Error generating version file:', error.message);

    // Fallback version if package.json can't be read
    const fallbackVersion = {
        version: 'v-dev',
        buildTime: new Date().toISOString()
    };

    const content = `// This file is auto-generated by generate-version.js
// Do not edit manually

export const VERSION_INFO = ${JSON.stringify(fallbackVersion, null, 2)};
`;

    const outputPath = path.join(__dirname, 'src', 'version.ts');
    fs.writeFileSync(outputPath, content, 'utf-8');

    console.log('⚠️  Using fallback version (package.json not available)');
}
